### ISSUE TITLE
Does the ADC sampling affect by the the RF frequency switch?

### ISSUE THREAD

**Issue by commthu** [analogdevicesinc/plutosdr-fw#19]
When i  swtich RF center frequecy, does the sampling affect by the the RF frequency switch? I wish during the frequency tunning,  the ADC keep working. This is very important for  my applications.

**Comment by rgetz** [comment]
It depends on your setup, but nominally, when switching the LO over 100MHz, a re-calibration is needed, and the act of calibration will cause samples to be stopped.

I think the driver is optimized to not return samples until the LO is locked, since most comms algorithms don't want to see things sweeping.

**Comment by tfcollins** [comment]
Fastlock profiles can remove most of this overhead: https://wiki.analog.com/resources/tools-software/linux-drivers/iio-transceiver/ad9361?s[]=fastlock#fastlock_mode

**Comment by mhennerich** [comment]
If you only tune the RX LO or if you disable automatic calibration mode you won’t see interruptions.

**Comment by mhennerich** [comment]
ok - close this.
