### ISSUE TITLE
Submodules can't be shallowed cloned

### ISSUE THREAD

**Issue by nunojpg** [analogdevicesinc/plutosdr-fw#24]
Submodules u-boot-xlnx, buildroot and linux currently refer to commits which are not tagged or branch HEAD.

This makes impossible for git submodule to do a shallow clone, which greatly increases download times and disk usage.

hdl currently refers to a commit tagged, so that one is fine.

The disk space currently used after a full clone is 3.1GB and a shallow clone would be 1.4GB

For releases please tag the commits used on the submodules and push them to github. The tag name is not relevant, any random name is fine, but could also be for eg. "for-plutosdr-fw-v0.29". This is just to make the git protocol expose this commits for a outside shallow clone.

**Comment by commodo** [comment]
I think this is more of a `git` functionality issue, rather than a problem with this repo, or the code in this repo.
The current instructions refer to using `git clone --recursive` ; I did not dig into it to check whether this can do shallow clones of submodules, but if it can't it's definitely a problem with `git`.

One approach I was thinking of, for this repo and for m2k-fw is to maybe try to integrate all this into a buildroot system; that would allow for more functionality, as well as allowing people to better customize their own images [tools on the image, etc] if they want to.

**Comment by nunojpg** [comment]
@commodo Yes, it's a limitation of GIT protocol on the wire. GIT only allows to request the remote for a tag or branch, but not to ask for a specific commit.

The builds could be much faster and smaller on disk with almost no effort. Just push tags into the submodules, for example:

tag 387d584d434 with for-plutosdr-fw-v0.31  into https://github.com/analogdevicesinc/linux

**Comment by nunojpg** [comment]
This limitation have since been fixed with a Git protocol update, see https://stackoverflow.com/a/43136160/1590596
